import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',

    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
        colors: {
            "surface-container-high": "#e7e8e9",
            "primary-container": "#eb0000",
            "surface-tint": "#c00100",
            "inverse-on-surface": "#f0f1f2",
            "on-tertiary": "#ffffff",
            "outline-variant": "#ebbbb4",
            background: "#f8f9fa",
            "surface-dim": "#d9dadb",
            "on-error-container": "#93000a",
            "on-secondary-fixed": "#1a1c1e",
            "on-error": "#ffffff",
            "on-tertiary-fixed-variant": "#3f484f",
            "surface-container-highest": "#e1e3e4",
            error: "#ba1a1a",
            "on-surface-variant": "#603e39",
            "on-background": "#191c1d",
            "secondary-fixed-dim": "#c6c6c9",
            "on-surface": "#191c1d",
            surface: "#f8f9fa",
            "inverse-primary": "#ffb4a8",
            secondary: "#5d5e61",
            "on-secondary": "#ffffff",
            "secondary-container": "#e2e2e5",
            "on-primary-container": "#fffbff",
            primary: "#FF6B00",
            "surface-container": "#edeeef",
            "tertiary-container": "#6d767e",
            "surface-bright": "#f8f9fa",
            "primary-fixed": "#ffdad4",
            "on-secondary-container": "#636467",
            "surface-container-low": "#f3f4f5",
            "tertiary-fixed": "#dbe4ed",
            "secondary-fixed": "#e2e2e5",
            outline: "#956d67",
            "on-tertiary-container": "#fcfcff",
            "tertiary-fixed-dim": "#bfc8d0",
            "error-container": "#ffdad6",
            "on-secondary-fixed-variant": "#454749",
            "inverse-surface": "#2e3132",
            "primary-fixed-dim": "#ffb4a8",
            "surface-container-lowest": "#ffffff",
            "on-tertiary-fixed": "#141d23",
            "surface-variant": "#e1e3e4",
            "on-primary-fixed-variant": "#930100",
            tertiary: "#545d65",
            "on-primary": "#ffffff",
            "on-primary-fixed": "#410000",
        },
        borderRadius: {
            DEFAULT: "0.125rem",
            lg: "0.25rem",
            xl: "0.5rem",
            full: "0.75rem",
        },
        spacing: {
            "container-max": "1440px",
            "margin-mobile": "16px",
            gutter: "24px",
            base: "8px",
            "margin-desktop": "40px",
        },
        fontFamily: {
            "label-md": ["Inter"],
            "label-sm": ["Inter"],
            "display-lg": ["Hanken Grotesk"],
            "headline-lg-mobile": ["Hanken Grotesk"],
            "headline-md": ["Hanken Grotesk"],
            "body-lg": ["Inter"],
            "body-md": ["Inter"],
            "headline-lg": ["Hanken Grotesk"],
        },
        fontSize: {
            "label-md": [
            "14px",
            { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" },
            ],
            "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
            "display-lg": [
            "48px",
            { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
            ],
            "headline-lg-mobile": [
            "28px",
            { lineHeight: "36px", fontWeight: "600" },
            ],
            "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
            "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
            "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
            "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        },
        },
    },

    plugins: [forms],
};
